#!/usr/bin/env ruby

if ARGV.length == 0 || ARGV[0] == "--help"
  puts "usage: xbackup [config-files..]"
  exit 0
end

require_relative "xbackup-class"
x = XBackup.new(ARGV, "force" => !!ENV["force"] )
x.log "force flag is #{x.force}"
x.go
x.stage "done"